import {createHash} from 'node:crypto';
import {mkdirSync, readFileSync, renameSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {nmshConfigDirectory} from '../configuration/paths.js';
import type {ShellId} from '../shell/adapters/ShellAdapter.js';

/**
 * The one Theme Bridge shell-environment sink.
 *
 * NMSh owns a persistent real shell; changing settings in the frontend cannot
 * reach into that process directly. Instead NMSh writes one generated,
 * validated, declarative file per shell syntax, and each ShellAdapter's own
 * bootstrap (static NMSh code, never the user's rc files) applies it from the
 * prompt hook:
 *
 *   if nmsh_bridge_begin <generation>; then
 *     nmsh_bridge_apply LS_COLORS '…'
 *     nmsh_bridge_clear LESS_TERMCAP_md
 *   fi
 *
 * Only allowlisted variable names and quoted literals appear; the file is
 * re-validated before every atomic replace. `apply` remembers the value it
 * replaced; `clear` restores it only if the variable still holds NMSh's own
 * value, so Independent removes exactly what NMSh set and nothing the user
 * changed. Nothing is written to history or the transcript.
 */

export const BRIDGE_ENV_VARIABLES = ['LS_COLORS', 'LESS_TERMCAP_mb', 'LESS_TERMCAP_md', 'LESS_TERMCAP_me', 'LESS_TERMCAP_so', 'LESS_TERMCAP_se',
  'LESS_TERMCAP_us', 'LESS_TERMCAP_ue', 'GROFF_NO_SGR'] as const;
export type BridgeEnvVariable = typeof BRIDGE_ENV_VARIABLES[number];
export type BridgeEnvironment = Partial<Record<BridgeEnvVariable, string>>;

const MAX_VALUE = 8 * 1024;
const ESC = '\u001B';

/** Values are printable ASCII plus ESC (for termcap sequences); anything else is refused. */
export function validEnvValue(value: string): boolean {
  return value.length <= MAX_VALUE && /^[ -~\u001b]*$/u.test(value);
}

/** zsh/Bash ANSI-C quoting: `$'…'` with `\e`, `\\` and `\'` as the only escapes. */
export function posixAnsiQuote(value: string): string {
  return `$'${value.replace(/\\/gu, '\\\\').replace(/'/gu, "\\'").replaceAll(ESC, '\\e')}'`;
}

/** Fish: single-quoted literal runs joined with bare `\e` escapes (fish concatenates adjacent tokens). */
export function fishLiteral(value: string): string {
  if (!value) return "''";
  return value.split(ESC).map(part => part ? `'${part.replace(/[\\']/gu, match => `\\${match}`)}'` : '').join('\\e') || "''";
}

export function bridgeEnvPath(shell: ShellId, env: NodeJS.ProcessEnv = process.env): string {
  return join(nmshConfigDirectory(env), 'theme-bridge', `environment.${shell === 'fish' ? 'fish' : shell}`);
}

/** Content-derived generation: identical environments never re-apply. */
export function environmentGeneration(values: BridgeEnvironment): string {
  const canonical = BRIDGE_ENV_VARIABLES.map(name => `${name}=${values[name] ?? ''}`).join('\n');
  return createHash('sha256').update(canonical).digest('hex').slice(0, 16);
}

export function renderEnvironmentFile(shell: ShellId, values: BridgeEnvironment): string {
  for (const [name, value] of Object.entries(values)) {
    if (!(BRIDGE_ENV_VARIABLES as readonly string[]).includes(name) || value === undefined || !validEnvValue(value)) throw new Error(`Refusing Theme Bridge value for ${name}.`);
  }
  const generation = environmentGeneration(values);
  const body = BRIDGE_ENV_VARIABLES.map(name => {
    const value = values[name];
    if (value === undefined) return `  nmsh_bridge_clear ${name}`;
    return `  nmsh_bridge_apply ${name} ${shell === 'fish' ? fishLiteral(value) : posixAnsiQuote(value)}`;
  });
  const header = '# Generated by NMSh Theme Bridge. Do not edit: NMSh replaces this file.\n';
  return shell === 'fish'
    ? `${header}if nmsh_bridge_begin ${generation}\n${body.join('\n')}\nend\n`
    : `${header}if nmsh_bridge_begin ${generation}; then\n${body.join('\n')}\nfi\n`;
}

const POSIX_LINE = /^  nmsh_bridge_(?:apply [A-Z][A-Z_a-z]* \$'(?:[^'\\]|\\[\\'e])*'|clear [A-Z][A-Z_a-z]*)$/u;
const FISH_LINE = /^  nmsh_bridge_(?:apply [A-Z][A-Z_a-z]* (?:'(?:[^'\\]|\\[\\'])*'|\\e)+|clear [A-Z][A-Z_a-z]*)$/u;

/** Strict grammar check of a generated file: nothing but the header, the guard and allowlisted calls. */
export function validateEnvironmentFile(shell: ShellId, content: string): boolean {
  const lines = content.split('\n');
  if (lines.at(-1) === '') lines.pop();
  const [header, open, ...rest] = lines;
  const close = rest.pop();
  if (header !== '# Generated by NMSh Theme Bridge. Do not edit: NMSh replaces this file.') return false;
  if (shell === 'fish' ? !/^if nmsh_bridge_begin [0-9a-f]{16}$/u.test(open ?? '') || close !== 'end'
    : !/^if nmsh_bridge_begin [0-9a-f]{16}; then$/u.test(open ?? '') || close !== 'fi') return false;
  if (rest.length !== BRIDGE_ENV_VARIABLES.length) return false;
  return rest.every((line, index) => (shell === 'fish' ? FISH_LINE : POSIX_LINE).test(line)
    && line.split(' ')[3] === BRIDGE_ENV_VARIABLES[index]);
}

/**
 * Writes the environment for every shell syntax (staged, validated, then
 * atomically renamed). New shells pick it up at their first prompt; running
 * shells at their next prompt.
 */
export function writeEnvironmentFiles(values: BridgeEnvironment, env: NodeJS.ProcessEnv = process.env): void {
  for (const shell of ['zsh', 'bash', 'fish'] as const) {
    const path = bridgeEnvPath(shell, env);
    const content = renderEnvironmentFile(shell, values);
    if (!validateEnvironmentFile(shell, content)) throw new Error('Generated Theme Bridge environment failed validation.');
    let current: string | undefined;
    try { current = readFileSync(path, 'utf8'); } catch { current = undefined; }
    if (current === content) continue;
    mkdirSync(dirname(path), {recursive: true, mode: 0o700});
    const staged = `${path}.${process.pid}.tmp`;
    writeFileSync(staged, content, {encoding: 'utf8', mode: 0o600});
    renameSync(staged, path);
  }
}

/**
 * The adapter-owned bootstrap that applies the environment file. Static NMSh
 * code; the only dynamic part is the quoted file path. The file is applied
 * only when it is a regular file owned by the user.
 */
export function bridgeBootstrap(shell: ShellId, path: string): string {
  if (shell === 'fish') {
    return `
function nmsh_bridge_begin
  test "$argv[1]" != "$__nmsh_bridge_generation"; or return 1
  set -g __nmsh_bridge_generation $argv[1]
end
function nmsh_bridge_apply
  set -l name $argv[1]
  set -l own __nmsh_bridge_own_$name
  set -l orig __nmsh_bridge_orig_$name
  if not set -q $own; or test "$$name" != "$$own"
    if set -q $name; set -g $orig $$name; else; set -e $orig; end
  end
  set -g $own $argv[2]
  set -gx $name $argv[2]
end
function nmsh_bridge_clear
  set -l name $argv[1]
  set -l own __nmsh_bridge_own_$name
  set -l orig __nmsh_bridge_orig_$name
  set -q $own; or return 0
  if test "$$name" = "$$own"
    if set -q $orig; set -gx $name $$orig; else; set -e $name; end
  end
  set -e $own; set -e $orig
end
function nmsh_bridge_sync
  set -l file ${fishQuoteLocal(path)}
  test -f $file -a -O $file; and source $file
end
`;
  }
  const quoted = posixAnsiQuote(path);
  if (shell === 'zsh') {
    return `
function nmsh_bridge_begin {
  [[ $1 != \${__nmsh_bridge_generation-} ]] || return 1
  typeset -g __nmsh_bridge_generation=$1
}
function nmsh_bridge_apply {
  local name=$1 own=__nmsh_bridge_own_$1 orig=__nmsh_bridge_orig_$1
  if (( ! \${(P)+own} )) || [[ \${(P)name-} != \${(P)own} ]]; then
    if (( \${(P)+name} )); then typeset -g $orig="\${(P)name}"; else unset $orig; fi
  fi
  typeset -g $own="$2"
  export $name="$2"
}
function nmsh_bridge_clear {
  local name=$1 own=__nmsh_bridge_own_$1 orig=__nmsh_bridge_orig_$1
  (( \${(P)+own} )) || return 0
  if [[ \${(P)name-} == \${(P)own} ]]; then
    if (( \${(P)+orig} )); then export $name="\${(P)orig}"; else unset $name; fi
  fi
  unset $own $orig
}
function nmsh_bridge_sync {
  local file=${quoted}
  [[ -f $file && -O $file ]] && source $file
}
`;
  }
  return `
nmsh_bridge_begin() {
  [[ "$1" != "\${__nmsh_bridge_generation-}" ]] || return 1
  __nmsh_bridge_generation=$1
}
nmsh_bridge_apply() {
  local name=$1 own=__nmsh_bridge_own_$1 orig=__nmsh_bridge_orig_$1
  if [[ -z "\${!own+x}" || "\${!name-}" != "\${!own}" ]]; then
    if [[ -n "\${!name+x}" ]]; then printf -v "$orig" '%s' "\${!name}"; else unset "$orig"; fi
  fi
  printf -v "$own" '%s' "$2"
  export "$name=$2"
}
nmsh_bridge_clear() {
  local name=$1 own=__nmsh_bridge_own_$1 orig=__nmsh_bridge_orig_$1
  [[ -n "\${!own+x}" ]] || return 0
  if [[ "\${!name-}" == "\${!own}" ]]; then
    if [[ -n "\${!orig+x}" ]]; then export "$name=\${!orig}"; else unset "$name"; fi
  fi
  unset "$own" "$orig"
}
nmsh_bridge_sync() {
  local file=${quoted}
  [[ -f $file && -O $file ]] && source "$file"
}
`;
}

function fishQuoteLocal(value: string): string {
  return `'${value.replace(/[\\']/gu, match => `\\${match}`)}'`;
}
