/** Decorative activity phrases only. They never describe verified work or determine success/failure.
 * Restored from the pre-PR #29 261-pair dictionary; reviewed and expanded.
 * Actual exit status, interrupts and process ownership come from structured execution state.
 */
export interface ActivityVerbPair { readonly active: string; readonly complete: string }

/** Paired phrases: one chosen at execution start and reused only for successful completion. */
export const ACTIVITY_VERBS: readonly ActivityVerbPair[] = [
  {active: "Cogitating", complete: "Cogitated"},
  {active: "Cerebrating", complete: "Cerebrated"},
  {active: "Pondering", complete: "Pondered"},
  {active: "Ruminating", complete: "Ruminated"},
  {active: "Mulling", complete: "Mulled"},
  {active: "Ideating", complete: "Ideated"},
  {active: "Imagining", complete: "Imagined"},
  {active: "Contemplating", complete: "Contemplated"},
  {active: "Deliberating", complete: "Deliberated"},
  {active: "Brainstorming", complete: "Brainstormed"},
  {active: "Reflecting", complete: "Reflected"},
  {active: "Wondering", complete: "Wondered"},
  {active: "Meditating", complete: "Meditated"},
  {active: "Speculating", complete: "Speculated"},
  {active: "Theorizing", complete: "Theorized"},
  {active: "Figuring", complete: "Figured"},
  {active: "Conceiving", complete: "Conceived"},
  {active: "Envisioning", complete: "Envisioned"},
  {active: "Visualizing", complete: "Visualized"},
  {active: "Daydreaming", complete: "Daydreamed"},
  {active: "Philosophizing", complete: "Philosophized"},
  {active: "Crafting", complete: "Crafted"},
  {active: "Assembling", complete: "Assembled"},
  {active: "Forging", complete: "Forged"},
  {active: "Fabricating", complete: "Fabricated"},
  {active: "Tinkering", complete: "Tinkered"},
  {active: "Mending", complete: "Mended"},
  {active: "Polishing", complete: "Polished"},
  {active: "Refining", complete: "Refined"},
  {active: "Weaving", complete: "Wove"},
  {active: "Sculpting", complete: "Sculpted"},
  {active: "Carving", complete: "Carved"},
  {active: "Molding", complete: "Molded"},
  {active: "Shaping", complete: "Shaped"},
  {active: "Designing", complete: "Designed"},
  {active: "Drafting", complete: "Drafted"},
  {active: "Sketching", complete: "Sketched"},
  {active: "Drawing", complete: "Drew"},
  {active: "Painting", complete: "Painted"},
  {active: "Sewing", complete: "Sewed"},
  {active: "Knitting", complete: "Knitted"},
  {active: "Stitching", complete: "Stitched"},
  {active: "Tailoring", complete: "Tailored"},
  {active: "Welding", complete: "Welded"},
  {active: "Soldering", complete: "Soldered"},
  {active: "Riveting", complete: "Riveted"},
  {active: "Gluing", complete: "Glued"},
  {active: "Taping", complete: "Taped"},
  {active: "Binding", complete: "Bound"},
  {active: "Erecting", complete: "Erected"},
  {active: "Cooking", complete: "Cooked"},
  {active: "Baking", complete: "Baked"},
  {active: "Brewing", complete: "Brewed"},
  {active: "Simmering", complete: "Simmered"},
  {active: "Stirring", complete: "Stirred"},
  {active: "Whisking", complete: "Whisked"},
  {active: "Kneading", complete: "Kneaded"},
  {active: "Roasting", complete: "Roasted"},
  {active: "Seasoning", complete: "Seasoned"},
  {active: "Marinating", complete: "Marinated"},
  {active: "Zesting", complete: "Zested"},
  {active: "Frying", complete: "Fried"},
  {active: "Sautéing", complete: "Sautéed"},
  {active: "Boiling", complete: "Boiled"},
  {active: "Steaming", complete: "Steamed"},
  {active: "Grilling", complete: "Grilled"},
  {active: "Broiling", complete: "Broiled"},
  {active: "Toasting", complete: "Toasted"},
  {active: "Microwaving", complete: "Microwaved"},
  {active: "Chopping", complete: "Chopped"},
  {active: "Dicing", complete: "Diced"},
  {active: "Mincing", complete: "Minced"},
  {active: "Slicing", complete: "Sliced"},
  {active: "Peeling", complete: "Peeled"},
  {active: "Grating", complete: "Grated"},
  {active: "Blending", complete: "Blended"},
  {active: "Pureeing", complete: "Pureed"},
  {active: "Mashing", complete: "Mashed"},
  {active: "Whipping", complete: "Whipped"},
  {active: "Glazing", complete: "Glazed"},
  {active: "Frolicking", complete: "Frolicked"},
  {active: "Moonwalking", complete: "Moonwalked"},
  {active: "Wandering", complete: "Wandered"},
  {active: "Roaming", complete: "Roamed"},
  {active: "Meandering", complete: "Meandered"},
  {active: "Zooming", complete: "Zoomed"},
  {active: "Shuffling", complete: "Shuffled"},
  {active: "Juggling", complete: "Juggled"},
  {active: "Spelunking", complete: "Spelunked"},
  {active: "Herding", complete: "Herded"},
  {active: "Wrangling", complete: "Wrangled"},
  {active: "Vibing", complete: "Vibed"},
  {active: "Dancing", complete: "Danced"},
  {active: "Prancing", complete: "Pranced"},
  {active: "Hopping", complete: "Hopped"},
  {active: "Jumping", complete: "Jumped"},
  {active: "Leaping", complete: "Leaped"},
  {active: "Bounding", complete: "Bounded"},
  {active: "Sprinting", complete: "Sprinted"},
  {active: "Jogging", complete: "Jogged"},
  {active: "Walking", complete: "Walked"},
  {active: "Strolling", complete: "Strolled"},
  {active: "Sauntering", complete: "Sauntered"},
  {active: "Ambling", complete: "Ambled"},
  {active: "Strutting", complete: "Strutted"},
  {active: "Marching", complete: "Marched"},
  {active: "Pacing", complete: "Paced"},
  {active: "Crawling", complete: "Crawled"},
  {active: "Creeping", complete: "Crept"},
  {active: "Sneaking", complete: "Sneaked"},
  {active: "Sliding", complete: "Slid"},
  {active: "Gliding", complete: "Glided"},
  {active: "Skating", complete: "Skated"},
  {active: "Skiing", complete: "Skied"},
  {active: "Surfing", complete: "Surfed"},
  {active: "Swimming", complete: "Swam"},
  {active: "Diving", complete: "Dived"},
  {active: "Floating", complete: "Floated"},
  {active: "Crunching", complete: "Crunched"},
  {active: "Combobulating", complete: "Combobulated"},
  {active: "Noodling", complete: "Noodled"},
  {active: "Doodling", complete: "Doodled"},
  {active: "Fiddling", complete: "Fiddled"},
  {active: "Finessing", complete: "Finessed"},
  {active: "Whirring", complete: "Whirred"},
  {active: "Wibbling", complete: "Wibbled"},
  {active: "Wobbling", complete: "Wobbled"},
  {active: "Conjuring", complete: "Conjured"},
  {active: "Untangling", complete: "Untangled"},
  {active: "Unfurling", complete: "Unfurled"},
  {active: "Percolating", complete: "Percolated"},
  {active: "Bubbling", complete: "Bubbled"},
  {active: "Fizzing", complete: "Fizzed"},
  {active: "Sizzling", complete: "Sizzled"},
  {active: "Popping", complete: "Popped"},
  {active: "Crackling", complete: "Crackled"},
  {active: "Snapping", complete: "Snapped"},
  {active: "Rustling", complete: "Rustled"},
  {active: "Humming", complete: "Hummed"},
  {active: "Buzzing", complete: "Buzzed"},
  {active: "Beeping", complete: "Beeped"},
  {active: "Booping", complete: "Booped"},
  {active: "Clicking", complete: "Clicked"},
  {active: "Clacking", complete: "Clacked"},
  {active: "Tapping", complete: "Tapped"},
  {active: "Rattling", complete: "Rattled"},
  {active: "Jingling", complete: "Jingled"},
  {active: "Tinkling", complete: "Tinkled"},
  {active: "Chiming", complete: "Chimed"},
  {active: "Gurgling", complete: "Gurgled"},
  {active: "Slurping", complete: "Slurped"},
  {active: "Munching", complete: "Munched"},
  {active: "Sniffing", complete: "Sniffed"},
  {active: "Snooping", complete: "Snooped"},
  {active: "Sleuthing", complete: "Sleuthed"},
  {active: "Meowing", complete: "Meowed"},
  {active: "Purring", complete: "Purred"},
  {active: "Pawing", complete: "Pawed"},
  {active: "Whiskering", complete: "Whiskered"},
  {active: "Loafing", complete: "Loafed"},
  {active: "Catnapping", complete: "Catnapped"},
  {active: "Pouncing", complete: "Pounced"},
  {active: "Prowling", complete: "Prowled"},
  {active: "Scratching", complete: "Scratched"},
  {active: "Spitting", complete: "Spat"},
  {active: "Yowling", complete: "Yowled"},
  {active: "Caterwauling", complete: "Caterwauled"},
  {active: "Chirping", complete: "Chirped"},
  {active: "Chattering", complete: "Chattered"},
  {active: "Trilling", complete: "Trilled"},
  {active: "Snuggling", complete: "Snuggled"},
  {active: "Cuddling", complete: "Cuddled"},
  {active: "Nuzzling", complete: "Nuzzled"},
  {active: "Rubbing", complete: "Rubbed"},
  {active: "Grooming", complete: "Groomed"},
  {active: "Licking", complete: "Licked"},
  {active: "Washing", complete: "Washed"},
  {active: "Bathing", complete: "Bathed"},
  {active: "Sleeping", complete: "Slept"},
  {active: "Dozing", complete: "Dozed"},
  {active: "Snoozing", complete: "Snoozed"},
  {active: "Resting", complete: "Rested"},
  {active: "Relaxing", complete: "Relaxed"},
  {active: "Lounging", complete: "Lounged"},
  {active: "Stretching", complete: "Stretched"},
  {active: "Yawning", complete: "Yawned"},
  {active: "Basting", complete: "Basted"},
  {active: "Caramelizing", complete: "Caramelized"},
  {active: "Poaching", complete: "Poached"},
  {active: "Braising", complete: "Braised"},
  {active: "Barbecuing", complete: "Barbecued"},
  {active: "Parboiling", complete: "Parboiled"},
  {active: "Infusing", complete: "Infused"},
  {active: "Sifting", complete: "Sifted"},
  {active: "Sprinkling", complete: "Sprinkled"},
  {active: "Drizzling", complete: "Drizzled"},
  {active: "Scooping", complete: "Scooped"},
  {active: "Ladling", complete: "Ladled"},
  {active: "Dunking", complete: "Dunked"},
  {active: "Nibbling", complete: "Nibbled"},
  {active: "Snacking", complete: "Snacked"},
  {active: "Feasting", complete: "Feasted"},
  {active: "Grazing", complete: "Grazed"},
  {active: "Plating", complete: "Plated"},
  {active: "Garnishing", complete: "Garnished"},
  {active: "Crumbing", complete: "Crumbed"},
  {active: "Frosting", complete: "Frosted"},
  {active: "Icing", complete: "Iced"},
  {active: "Dusting", complete: "Dusted"},
  {active: "Tempering", complete: "Tempered"},
  {active: "Fermenting", complete: "Fermented"},
  {active: "Pickling", complete: "Pickled"},
  {active: "Churning", complete: "Churned"},
  {active: "Candying", complete: "Candied"},
  {active: "Stir-frying", complete: "Stir-fried"},
  {active: "Flambéing", complete: "Flambéed"},
  {active: "Dabbling", complete: "Dabbled"},
  {active: "Spritzing", complete: "Spritzed"},
  {active: "Zigzagging", complete: "Zigzagged"},
  {active: "Nourishing", complete: "Nourished"},
  {active: "Browning", complete: "Browned"},
  {active: "Dipping", complete: "Dipped"},
  {active: "Savoring", complete: "Savored"},
  {active: "Scampering", complete: "Scampered"},
  {active: "Galloping", complete: "Galloped"},
  {active: "Trotting", complete: "Trotted"},
  {active: "Cantering", complete: "Cantered"},
  {active: "Nesting", complete: "Nested"},
  {active: "Foraging", complete: "Foraged"},
  {active: "Fluttering", complete: "Fluttered"},
  {active: "Flapping", complete: "Flapped"},
  {active: "Swooping", complete: "Swooped"},
  {active: "Soaring", complete: "Soared"},
  {active: "Skittering", complete: "Skittered"},
  {active: "Scurrying", complete: "Scurried"},
  {active: "Burrowing", complete: "Burrowed"},
  {active: "Digging", complete: "Dug"},
  {active: "Snuffling", complete: "Snuffled"},
  {active: "Whinnying", complete: "Whinnied"},
  {active: "Barking", complete: "Barked"},
  {active: "Woofing", complete: "Woofed"},
  {active: "Yipping", complete: "Yipped"},
  {active: "Howling", complete: "Howled"},
  {active: "Growling", complete: "Growled"},
  {active: "Chirruping", complete: "Chirruped"},
  {active: "Tweeting", complete: "Tweeted"},
  {active: "Squawking", complete: "Squawked"},
  {active: "Hooting", complete: "Hooted"},
  {active: "Cooing", complete: "Cooed"},
  {active: "Quacking", complete: "Quacked"},
  {active: "Honking", complete: "Honked"},
  {active: "Croaking", complete: "Croaked"},
  {active: "Ribbiting", complete: "Ribbited"},
  {active: "Bellowing", complete: "Bellowed"},
  {active: "Roaring", complete: "Roared"},
  {active: "Trumpeting", complete: "Trumpeted"},
  {active: "Wagging", complete: "Wagged"},
  {active: "Slinking", complete: "Slunk"},
  {active: "Curling up", complete: "Curled up"},
  {active: "Paddling", complete: "Paddled"},
  {active: "Perching", complete: "Perched"},
  {active: "Preening", complete: "Preened"},
  {active: "Sunbathing", complete: "Sunbathed"},
  {active: "Hibernating", complete: "Hibernated"},
  {active: "Murmuring", complete: "Murmured"},
  {active: "Waddling", complete: "Waddled"},
  {active: "Calligraphing", complete: "Calligraphed"},
  {active: "Lettering", complete: "Lettered"},
  {active: "Inking", complete: "Inked"},
  {active: "Coloring", complete: "Colored"},
  {active: "Shading", complete: "Shaded"},
  {active: "Crosshatching", complete: "Crosshatched"},
  {active: "Outlining", complete: "Outlined"},
  {active: "Stippling", complete: "Stippled"},
  {active: "Blotting", complete: "Blotted"},
  {active: "Dabbing", complete: "Dabbed"},
  {active: "Sponging", complete: "Sponged"},
  {active: "Smudging", complete: "Smudged"},
  {active: "Blurring", complete: "Blurred"},
  {active: "Etching", complete: "Etched"},
  {active: "Engraving", complete: "Engraved"},
  {active: "Embossing", complete: "Embossed"},
  {active: "Hammering", complete: "Hammered"},
  {active: "Sawing", complete: "Sawed"},
  {active: "Sanding", complete: "Sanded"},
  {active: "Varnishing", complete: "Varnished"},
  {active: "Lacquering", complete: "Lacquered"},
  {active: "Beading", complete: "Beaded"},
  {active: "Crocheting", complete: "Crocheted"},
  {active: "Macraméing", complete: "Macraméed"},
  {active: "Quilting", complete: "Quilted"},
  {active: "Patchworking", complete: "Patchworked"},
  {active: "Felting", complete: "Felted"},
  {active: "Origami-making", complete: "Made origami"},
  {active: "Pottering", complete: "Pottered"},
  {active: "Wheel-throwing", complete: "Threw pots"},
  {active: "Potting", complete: "Potted"},
  {active: "Kiln-firing", complete: "Fired the kiln"},
  {active: "Bookbinding", complete: "Bound books"},
  {active: "Screenprinting", complete: "Screenprinted"},
  {active: "Collaging", complete: "Collaged"},
  {active: "Knotting", complete: "Knotted"},
  {active: "Harmonizing", complete: "Harmonized"},
  {active: "Improvising", complete: "Improvised"},
  {active: "Serenading", complete: "Serenaded"},
  {active: "Crooning", complete: "Crooned"},
  {active: "Singing", complete: "Sang"},
  {active: "Whistling", complete: "Whistled"},
  {active: "Warbling", complete: "Warbled"},
  {active: "Riffing", complete: "Riffed"},
  {active: "Strumming", complete: "Strummed"},
  {active: "Plucking", complete: "Plucked"},
  {active: "Pizzicato playing", complete: "Played pizzicato"},
  {active: "Drumming", complete: "Drummed"},
  {active: "Beatboxing", complete: "Beatboxed"},
  {active: "Scatting", complete: "Scatted"},
  {active: "Rapping", complete: "Rapped"},
  {active: "Yodeling", complete: "Yodeled"},
  {active: "Jamming", complete: "Jammed"},
  {active: "Grooving", complete: "Grooved"},
  {active: "Headbanging", complete: "Headbanged"},
  {active: "Swaying", complete: "Swayed"},
  {active: "Twisting", complete: "Twisted"},
  {active: "Twirling", complete: "Twirled"},
  {active: "Pirouetting", complete: "Pirouetted"},
  {active: "Waltzing", complete: "Waltzed"},
  {active: "Tangoing", complete: "Tangoed"},
  {active: "Salsa dancing", complete: "Salsa danced"},
  {active: "Two-stepping", complete: "Two-stepped"},
  {active: "Toe-tapping", complete: "Toe-tapped"},
  {active: "Finger-snapping", complete: "Finger-snapped"},
  {active: "Rhyming", complete: "Rhymed"},
  {active: "Composing", complete: "Composed"},
  {active: "Arranging", complete: "Arranged"},
  {active: "Conducting", complete: "Conducted"},
  {active: "Rambling", complete: "Rambled"},
  {active: "Trekking", complete: "Trekked"},
  {active: "Hiking", complete: "Hiked"},
  {active: "Clambering", complete: "Clambered"},
  {active: "Scrambling", complete: "Scrambled"},
  {active: "Scaling", complete: "Scaled"},
  {active: "Rappelling", complete: "Rappelled"},
  {active: "Belaying", complete: "Belayed"},
  {active: "Abseiling", complete: "Abseiled"},
  {active: "Rowing", complete: "Rowed"},
  {active: "Canoeing", complete: "Canoed"},
  {active: "Kayaking", complete: "Kayaked"},
  {active: "Rafting", complete: "Rafted"},
  {active: "Sailing", complete: "Sailed"},
  {active: "Yachting", complete: "Yachted"},
  {active: "Snorkeling", complete: "Snorkeled"},
  {active: "Drifting", complete: "Drifted"},
  {active: "Cruising", complete: "Cruised"},
  {active: "Trundling", complete: "Trundled"},
  {active: "Rolling", complete: "Rolled"},
  {active: "Scooting", complete: "Scooted"},
  {active: "Skedaddling", complete: "Skedaddled"},
  {active: "Darting", complete: "Darted"},
  {active: "Dashing", complete: "Dashed"},
  {active: "Zipping", complete: "Zipped"},
  {active: "Tiptoeing", complete: "Tiptoed"},
  {active: "Tumbling", complete: "Tumbled"},
  {active: "Somersaulting", complete: "Somersaulted"},
  {active: "Cartwheeling", complete: "Cartwheeled"},
  {active: "Backflipping", complete: "Backflipped"},
  {active: "Vaulting", complete: "Vaulted"},
  {active: "Pole-vaulting", complete: "Pole-vaulted"},
  {active: "Bouldering", complete: "Bouldered"},
  {active: "Geocaching", complete: "Geocached"},
  {active: "Stargazing", complete: "Stargazed"},
  {active: "Cloudwatching", complete: "Cloudwatched"},
  {active: "Birdwatching", complete: "Birdwatched"},
  {active: "People-watching", complete: "People-watched"},
  {active: "Observing", complete: "Observed"},
  {active: "Magnifying", complete: "Magnified"},
  {active: "Peering", complete: "Peered"},
  {active: "Squinting", complete: "Squinted"},
  {active: "Graphing", complete: "Graphed"},
  {active: "Plotting", complete: "Plotted"},
  {active: "Triangulating", complete: "Triangulated"},
  {active: "Extrapolating", complete: "Extrapolated"},
  {active: "Interpolating", complete: "Interpolated"},
  {active: "Tabulating", complete: "Tabulated"},
  {active: "Number-crunching", complete: "Crunched numbers"},
  {active: "Abacus-twirling", complete: "Twirled an abacus"},
  {active: "Counting stars", complete: "Counted stars"},
  {active: "Planet-spotting", complete: "Spotted planets"},
  {active: "Comet-watching", complete: "Watched comets"},
  {active: "Microscoping", complete: "Used a microscope"},
  {active: "Spectating", complete: "Spectated"},
  {active: "Field-noting", complete: "Took field notes"},
  {active: "Star-charting", complete: "Charted stars"},
  {active: "Collecting pebbles", complete: "Collected pebbles"},
  {active: "Measuring shadows", complete: "Measured shadows"},
  {active: "Seashell-arranging", complete: "Arranged seashells"},
  {active: "Blossoming", complete: "Blossomed"},
  {active: "Blooming", complete: "Bloomed"},
  {active: "Budding", complete: "Budded"},
  {active: "Sprouting", complete: "Sprouted"},
  {active: "Germinating", complete: "Germinated"},
  {active: "Growing", complete: "Grew"},
  {active: "Rooting", complete: "Rooted"},
  {active: "Branching", complete: "Branched"},
  {active: "Photosynthesizing", complete: "Photosynthesized"},
  {active: "Pollinating", complete: "Pollinated"},
  {active: "Seedling-tending", complete: "Tended seedlings"},
  {active: "Watering", complete: "Watered"},
  {active: "Mulching", complete: "Mulched"},
  {active: "Raking", complete: "Raked"},
  {active: "Pruning", complete: "Pruned"},
  {active: "Planting", complete: "Planted"},
  {active: "Sowing", complete: "Sowed"},
  {active: "Harvesting", complete: "Harvested"},
  {active: "Weeding", complete: "Weeded"},
  {active: "Composting", complete: "Composted"},
  {active: "Tending roses", complete: "Tended roses"},
  {active: "Raining", complete: "Rained"},
  {active: "Snowing", complete: "Snowed"},
  {active: "Hailing", complete: "Hailed"},
  {active: "Thundering", complete: "Thundered"},
  {active: "Breezing", complete: "Breezed"},
  {active: "Gusting", complete: "Gusted"},
  {active: "Rippling", complete: "Rippled"},
  {active: "Shimmering", complete: "Shimmered"},
  {active: "Glittering", complete: "Glittered"},
  {active: "Glistening", complete: "Glistened"},
  {active: "Sparkling", complete: "Sparkled"},
  {active: "Twinkling", complete: "Twinkled"},
  {active: "Narrating", complete: "Narrated"},
  {active: "Storytelling", complete: "Told stories"},
  {active: "Whispering", complete: "Whispered"},
  {active: "Browsing books", complete: "Browsed books"},
  {active: "Page-turning", complete: "Turned pages"},
  {active: "Leafing through", complete: "Leafed through"},
  {active: "Bookmarking", complete: "Bookmarked"},
  {active: "Scribbling", complete: "Scribbled"},
  {active: "Journaling", complete: "Journaled"},
  {active: "Freewriting", complete: "Freewrote"},
  {active: "Annotating", complete: "Annotated"},
  {active: "Dramatizing", complete: "Dramatized"},
  {active: "Acting", complete: "Acted"},
  {active: "Rehearsing", complete: "Rehearsed"},
  {active: "Reciting", complete: "Recited"},
  {active: "Quoting", complete: "Quoted"},
  {active: "Monologuing", complete: "Monologued"},
  {active: "Dialoguing", complete: "Dialogued"},
  {active: "Captioning", complete: "Captioned"},
  {active: "Alliterating", complete: "Alliterated"},
  {active: "Pun-making", complete: "Made puns"},
  {active: "Riddling", complete: "Riddled"},
  {active: "Riddle-solving", complete: "Solved riddles"},
  {active: "Plot-twisting", complete: "Twisted the plot"},
  {active: "Character-sketching", complete: "Sketched characters"},
  {active: "Worldbuilding", complete: "Built worlds"},
  {active: "Imagining dragons", complete: "Imagined dragons"},
  {active: "Fable-spinning", complete: "Spun fables"},
  {active: "Lore-building", complete: "Built lore"},
  {active: "Confetti-tossing", complete: "Tossed confetti"},
  {active: "Bubble-blowing", complete: "Blew bubbles"},
  {active: "Bubble-popping", complete: "Popped bubbles"},
  {active: "Balloon-twisting", complete: "Twisted balloons"},
  {active: "Party-hatting", complete: "Wore a party hat"},
  {active: "Hula-hooping", complete: "Hula-hooped"},
  {active: "Limboing", complete: "Limboed"},
  {active: "Pogo-sticking", complete: "Pogo-sticked"},
  {active: "Sock-sliding", complete: "Slid in socks"},
  {active: "Pillow-forting", complete: "Built pillow forts"},
  {active: "Blanket-burritoing", complete: "Became a blanket burrito"},
  {active: "Couch-surfing", complete: "Couch-surfed"},
  {active: "Silly-walking", complete: "Silly-walked"},
  {active: "Air-guitaring", complete: "Air-guitared"},
  {active: "Finger-gunning", complete: "Finger-gunned"},
  {active: "Jazz-handing", complete: "Jazz-handed"},
  {active: "Jazz-stepping", complete: "Jazz-stepped"},
  {active: "Eyebrow-raising", complete: "Raised an eyebrow"},
  {active: "Hat-tipping", complete: "Tipped a hat"},
  {active: "Winking", complete: "Winked"},
  {active: "Grinning", complete: "Grinned"},
  {active: "Giggling", complete: "Giggled"},
  {active: "Chuckling", complete: "Chuckled"},
  {active: "Snickering", complete: "Snickered"},
  {active: "Chortling", complete: "Chortled"},
  {active: "Guffawing", complete: "Guffawed"},
  {active: "Cackling", complete: "Cackled"},
  {active: "Tee-heeing", complete: "Tee-heed"},
  {active: "Whimsy-wrangling", complete: "Wrangled whimsy"},
  {active: "Mischief-making", complete: "Made mischief"},
  {active: "Shenaniganizing", complete: "Made shenanigans"},
  {active: "Goofing off", complete: "Goofed off"},
  {active: "Loitering", complete: "Loitered"},
  {active: "Lollygagging", complete: "Lollygagged"},
  {active: "Dillydallying", complete: "Dillydallied"},
  {active: "Dawdling", complete: "Dawdled"},
  {active: "Faffing", complete: "Faffed"},
  {active: "Bumbling", complete: "Bumbled"},
  {active: "Fumbling", complete: "Fumbled"},
  {active: "Winging it", complete: "Winged it"},
  {active: "Wand-waving", complete: "Waved a wand"},
  {active: "Spellcasting", complete: "Cast a spell"},
  {active: "Potion-mixing", complete: "Mixed potions"},
  {active: "Cauldron-stirring", complete: "Stirred a cauldron"},
  {active: "Crystal-gazing", complete: "Gazed into crystals"},
  {active: "Charm-making", complete: "Made charms"},
  {active: "Enchanting", complete: "Enchanted"},
  {active: "Bewitching", complete: "Bewitched"},
  {active: "Transfiguring", complete: "Transfigured"},
  {active: "Transmuting", complete: "Transmuted"},
  {active: "Levitation-practicing", complete: "Practiced levitation"},
  {active: "Teleporting", complete: "Teleported"},
  {active: "Summoning", complete: "Summoned"},
  {active: "Incanting", complete: "Incanted"},
  {active: "Runecarving", complete: "Carved runes"},
  {active: "Rune-reading", complete: "Read runes"},
  {active: "Star-summoning", complete: "Summoned stars"},
  {active: "Dragon-taming", complete: "Tamed dragons"},
  {active: "Phoenix-rising", complete: "Rose like a phoenix"},
  {active: "Cloak-swirling", complete: "Swirled a cloak"},
  {active: "Hat-conjuring", complete: "Conjured a hat"},
  {active: "Rabbit-pulling", complete: "Pulled a rabbit"},
  {active: "Smoke-puffing", complete: "Puffed smoke"},
  {active: "Sparkle-casting", complete: "Cast sparkles"},
  {active: "Dice-rolling", complete: "Rolled dice"},
  {active: "Card-shuffling", complete: "Shuffled cards"},
  {active: "Card-dealing", complete: "Dealt cards"},
  {active: "Puzzle-solving", complete: "Solved puzzles"},
  {active: "Maze-wandering", complete: "Wandered a maze"},
  {active: "Questing", complete: "Quested"},
  {active: "Loot-gathering", complete: "Gathered loot"},
  {active: "Treasure-hunting", complete: "Hunted treasure"},
  {active: "Chest-opening", complete: "Opened chests"},
  {active: "Token-moving", complete: "Moved tokens"},
  {active: "Level-grinding", complete: "Ground levels"},
  {active: "Speedrunning", complete: "Speedran"},
  {active: "Parkouring", complete: "Parkoured"},
  {active: "Button-mashing", complete: "Mashed buttons"},
  {active: "Joystick-wiggling", complete: "Wiggled a joystick"},
  {active: "Victory-dancing", complete: "Victory-danced"},
  {active: "High-fiving", complete: "High-fived"},
  {active: "Fist-bumping", complete: "Fist-bumped"},
  {active: "Coin-flipping", complete: "Flipped coins"},
  {active: "Marble-counting", complete: "Counted marbles"},
  {active: "Chess-thinking", complete: "Thought about chess"},
  {active: "Checkers-hopping", complete: "Hopped checkers"},
  {active: "Domino-stacking", complete: "Stacked dominoes"},
  {active: "Tower-building", complete: "Built towers"},
  {active: "Jenga-juggling", complete: "Juggled Jenga"},
  {active: "Orbiting", complete: "Orbited"},
  {active: "Drifting in space", complete: "Drifted in space"},
  {active: "Rocketing", complete: "Rocketed"},
  {active: "Star-hopping", complete: "Star-hopped"},
  {active: "Moon-hopping", complete: "Moon-hopped"},
  {active: "Satellite-spotting", complete: "Spotted satellites"},
  {active: "Nebula-gazing", complete: "Gazed at nebulae"},
  {active: "Comet-chasing", complete: "Chased comets"},
  {active: "Meteor-watching", complete: "Watched meteors"},
  {active: "Constellation-hunting", complete: "Hunted constellations"},
  {active: "Asteroid-dodging", complete: "Dodged asteroids"},
  {active: "Spacesuit-checking", complete: "Checked a spacesuit"},
  {active: "Galaxy-roaming", complete: "Roamed galaxies"},
  {active: "Blackhole-peeking", complete: "Peeked at black holes"},
  {active: "Cosmic-doodling", complete: "Doodled cosmos"},
  {active: "Gravity-bending", complete: "Bent gravity"},
  {active: "Time-warping", complete: "Warped time"},
  {active: "Wormhole-hopping", complete: "Hopped wormholes"},
  {active: "Star-dusting", complete: "Dusted stars"},
  {active: "Moonbeam-catching", complete: "Caught moonbeams"},
  {active: "Solar-sailing", complete: "Solar-sailed"},
  {active: "Lantern-lighting", complete: "Lit lanterns"},
  {active: "Candle-making", complete: "Made candles"},
  {active: "Firefly-chasing", complete: "Chased fireflies"},
  {active: "Kite-flying", complete: "Flew kites"},
  {active: "Paper-plane-making", complete: "Made paper planes"},
  {active: "Sandcastle-building", complete: "Built sandcastles"},
  {active: "Stone-skimming", complete: "Skimmed stones"},
  {active: "Pebble-stacking", complete: "Stacked pebbles"},
  {active: "Tea-sipping", complete: "Sipped tea"},
  {active: "Coffee-slurping", complete: "Slurped coffee"},
  {active: "Cocoa-stirring", complete: "Stirred cocoa"},
  {active: "Cloud-counting", complete: "Counted clouds"},
  {active: "Shadow-chasing", complete: "Chased shadows"},
  {active: "Sunset-watching", complete: "Watched sunsets"},
  {active: "Sunrise-catching", complete: "Caught sunrises"},
  {active: "Breeze-catching", complete: "Caught a breeze"},
  {active: "Puddle-jumping", complete: "Jumped puddles"},
  {active: "Snowflake-catching", complete: "Caught snowflakes"},
  {active: "Leaf-crunching", complete: "Crunched leaves"},
  {active: "Acorn-collecting", complete: "Collected acorns"},
  {active: "Shell-hunting", complete: "Hunted shells"},
  {active: "Pebble-polishing", complete: "Polished pebbles"},
  {active: "Thread-spooling", complete: "Spooled thread"},
  {active: "Yarn-winding", complete: "Wound yarn"},
  {active: "Ribbon-curling", complete: "Curled ribbons"},
  {active: "Bow-tying", complete: "Tied bows"},
  {active: "Knuckle-cracking", complete: "Cracked knuckles"},
  {active: "Desk-doodling", complete: "Doodled on a desk"},
  {active: "Window-gazing", complete: "Gazed out a window"},
  {active: "Clock-watching", complete: "Watched the clock"},
  {active: "Sundial-reading", complete: "Read a sundial"},
  {active: "Map-unfolding", complete: "Unfolded a map"},
  {active: "Compass-twirling", complete: "Twirled a compass"},
  {active: "Bread-proofing", complete: "Proofed bread"},
  {active: "Noodle-slurping", complete: "Slurped noodles"},
  {active: "Dumpling-pleating", complete: "Pleated dumplings"},
  {active: "Pancake-flipping", complete: "Flipped pancakes"},
  {active: "Waffle-ironing", complete: "Ironed waffles"},
  {active: "Pie-crimping", complete: "Crimped a pie"},
  {active: "Jam-simmering", complete: "Simmered jam"},
  {active: "Sourdough-feeding", complete: "Fed the sourdough"},
  {active: "Lemonade-stirring", complete: "Stirred lemonade"},
  {active: "Popcorn-popping", complete: "Popped popcorn"},
  {active: "Marshmallow-toasting", complete: "Toasted marshmallows"},
  {active: "Kettle-whistling", complete: "Whistled like a kettle"},
  {active: "Lighthouse-keeping", complete: "Kept a lighthouse"},
  {active: "Harbor-watching", complete: "Watched the harbor"},
  {active: "Paper-crane-making", complete: "Made paper cranes"},
  {active: "Lantern-floating", complete: "Floated lanterns"},
  {active: "Pinwheel-spinning", complete: "Spun pinwheels"},
  {active: "Yo-yoing", complete: "Yo-yoed"},
  {active: "Cat's-cradling", complete: "Played cat's cradle"},
  {active: "Hopscotching", complete: "Hopscotched"},
  {active: "Jump-roping", complete: "Jump-roped"},
  {active: "Marble-rolling", complete: "Rolled marbles"},
  {active: "Chalk-drawing", complete: "Drew with chalk"},
  {active: "Hand-shadowing", complete: "Cast hand shadows"},
  {active: "Treehouse-building", complete: "Built a treehouse"},
  {active: "Hammock-swinging", complete: "Swung in a hammock"},
  {active: "Campfire-tending", complete: "Tended a campfire"},
  {active: "S'more-making", complete: "Made s'mores"},
  {active: "Trail-mixing", complete: "Mixed trail mix"},
  {active: "Pond-skimming", complete: "Skimmed a pond"},
  {active: "Lily-padding", complete: "Hopped lily pads"},
  {active: "Tadpole-watching", complete: "Watched tadpoles"},
  {active: "Beekeeping", complete: "Kept bees"},
  {active: "Butterfly-netting", complete: "Netted butterflies"},
  {active: "Moss-gathering", complete: "Gathered moss"},
  {active: "Fern-unfurling", complete: "Unfurled ferns"},
  {active: "Mushroom-spotting", complete: "Spotted mushrooms"},
  {active: "Orchard-wandering", complete: "Wandered an orchard"},
  {active: "Windmill-turning", complete: "Turned a windmill"},
  {active: "Weathervane-spinning", complete: "Spun a weathervane"},
  {active: "Snow-angeling", complete: "Made snow angels"},
  {active: "Snowman-rolling", complete: "Rolled a snowman"},
  {active: "Sled-riding", complete: "Rode a sled"},
  {active: "Mitten-knitting", complete: "Knitted mittens"},
  {active: "Scarf-winding", complete: "Wound a scarf"},
  {active: "Gift-wrapping", complete: "Wrapped gifts"},
  {active: "Card-writing", complete: "Wrote cards"},
  {active: "Letter-sealing", complete: "Sealed a letter"},
  {active: "Stamp-collecting", complete: "Collected stamps"},
  {active: "Typewriter-clacking", complete: "Clacked a typewriter"},
  {active: "Record-spinning", complete: "Spun records"},
  {active: "Metronome-ticking", complete: "Ticked a metronome"},
  {active: "Music-box-winding", complete: "Wound a music box"},
  {active: "Lullaby-humming", complete: "Hummed a lullaby"},
  {active: "Harp-strumming", complete: "Strummed a harp"},
  {active: "Bell-ringing", complete: "Rang bells"},
  {active: "Whistle-carving", complete: "Carved whistles"},
  {active: "Sail-mending", complete: "Mended sails"},
  {active: "Rope-coiling", complete: "Coiled rope"},
  {active: "Net-casting", complete: "Cast a net"},
  {active: "Anchor-dropping", complete: "Dropped anchor"},
  {active: "Tide-pooling", complete: "Explored tide pools"},
  {active: "Sea-glass-hunting", complete: "Hunted sea glass"},
];

/** Stable across redraw, resize, replay and reattachment: it depends only on the command text and when it started, never on a window's own numbering. */
export function selectActivityVerb(command: string, startedAt: number, previous?: ActivityVerbPair): ActivityVerbPair {
  const seed = `${Math.trunc(startedAt)}:${command}`;
  let hash = 2166136261;
  for (let i = 0; i < seed.length; i++) hash = Math.imul(hash ^ seed.charCodeAt(i), 16777619) >>> 0;
  let index = hash % ACTIVITY_VERBS.length;
  if (previous && ACTIVITY_VERBS.length > 1 && ACTIVITY_VERBS[index]!.active === previous.active) index = (index + 1) % ACTIVITY_VERBS.length;
  return ACTIVITY_VERBS[index]!;
}
